-- Optimised version of q.sql generated by OpenAI's GPT-5 mini.
--      Output confirmed identical.

\copy (
    WITH 
        xref_1 AS (
            SELECT
                wof_id
                    AS "WOF_ID",
                name
                    AS "NAME",
                adm0name
                    AS "ADM0NAME",
                adm1name
                    AS "ADM1NAME",
                longitude
                    AS "LONGITUDE",
                latitude
                    AS "LATITUDE",
                geom
                    AS geometry
            FROM 
                populated_places_expanded
            GROUP BY 
                wof_id, 
                name, 
                adm0name, 
                adm1name, 
                longitude, 
                latitude, 
                geom
        ),
        xref_2 AS (
            SELECT
                id,
                CASE COALESCE("Density", '')
                    WHEN 'Heavy'  THEN 3
                    WHEN 'Medium' THEN 2
                    WHEN 'Light'  THEN 1
                    ELSE 0
                END 
                    AS rank,
                (TO_DATE(SUBSTRING("Start" FROM 1 FOR 7), 'YYYYDDD') + i)::date 
                    AS day,
                geometry
            FROM 
                public.hms_smokes{{YEAR}}
            CROSS JOIN 
                LATERAL generate_series(
                    0,
                    (TO_DATE(SUBSTRING("End" FROM 1 FOR 7), 'YYYYDDD') - TO_DATE(SUBSTRING("Start" FROM 1 FOR 7), 'YYYYDDD'))::int
                ) 
                    AS i
        ),
        xref_3 AS (
            SELECT
                x1."WOF_ID",
                x1."NAME",
                x1."ADM0NAME",
                x1."ADM1NAME",
                x1."LONGITUDE",
                x1."LATITUDE",
                x2.day,
                MAX(x2.rank) 
                    AS rank
            FROM 
                xref_1 x1
            LEFT JOIN 
                xref_2 x2
                    ON ST_Intersects(x1.geometry, x2.geometry)
            GROUP BY
                x1."WOF_ID", 
                x1."NAME", 
                x1."ADM0NAME", 
                x1."ADM1NAME",
                x1."LONGITUDE", 
                x1."LATITUDE", 
                x2.day
        )
        SELECT
            "WOF_ID",
            "NAME",
            "ADM0NAME",
            "ADM1NAME",
            "LONGITUDE",
            "LATITUDE",
            COUNT(CASE WHEN rank = 1 THEN 1 END) 
                AS "Smoke_days_light_point",
            COUNT(CASE WHEN rank = 2 THEN 1 END) 
                AS "Smoke_days_medium_point",
            COUNT(CASE WHEN rank = 3 THEN 1 END) 
                AS "Smoke_days_heavy_point",
            COUNT(CASE WHEN rank = 0 THEN 1 END) 
                AS "Smoke_days_undefined_point",
            (COUNT(CASE WHEN rank = 1 THEN 1 END)
            + COUNT(CASE WHEN rank = 2 THEN 1 END)
            + COUNT(CASE WHEN rank = 3 THEN 1 END)
            + COUNT(CASE WHEN rank = 0 THEN 1 END)) 
                AS "Smoke_days_aggregate_point"
        FROM 
            xref_3
        GROUP BY 
            "WOF_ID", 
            "NAME", 
            "ADM0NAME", 
            "ADM1NAME", 
            "LONGITUDE", 
            "LATITUDE"
        ORDER BY 
            "WOF_ID"
) TO '/Users/williamchuter-davies/Downloads/wfrtl_composite{{YEAR}}.csv' WITH CSV HEADER;
